import '../styles/globals.css';
import type { AppProps } from 'next/app';

import { QueryClient, QueryClientProvider} from 'react-query';
import Head from 'next/head';
import Nav from './comps/Nav';
const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
          <title>MyMovies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/movie.png" />
      </Head>
      <Nav />
      <QueryClientProvider client={queryClient}>
        <Component {...pageProps} />
      </QueryClientProvider>
    </>
  )
}
